# Generated by Django 5.0.2 on 2024-02-22 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.CharField(max_length=512)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.tree')),
            ],
        ),
    ]
